# Generated by Django 3.2.10 on 2022-01-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_game_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('O', 'ongoing'), ('A', 'abandoned'), ('C', 'completed')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='game',
            name='fen',
            field=models.CharField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1', max_length=90),
        ),
    ]
