# Generated by Django 3.2.10 on 2022-01-19 12:15

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220115_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='black_last_move_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='black_timer',
            field=models.DurationField(default=datetime.timedelta(0), validators=[core.models.validate_min_timer]),
        ),
        migrations.AddField(
            model_name='game',
            name='white_last_move_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='white_timer',
            field=models.DurationField(default=datetime.timedelta(0), validators=[core.models.validate_min_timer]),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('O', 'ongoing'), ('A', 'abandoned'), ('C', 'checkmate'), ('T', 'timeout'), ('D', 'draw')], default='O', max_length=1),
        ),
    ]
