# Generated by Django 3.2.10 on 2022-01-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220119_1215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
